### ISSUE TITLE
Scripts seems to not be working

### ISSUE THREAD

**Issue by Soul-Burn** [DeniSix/twitch-vlc-userscript#2]
The twitch player has changed in the last couple of months, migrating the controls to HTML5.
It might have stopped the script from working.

I however do not see any errors in the console coming from the script.

**Comment by DeniSix** [comment]
Please try [this](https://raw.githubusercontent.com/DeniSix/twitch-vlc-userscript/fix-1/twitch-vlc.user.js) version.
